insert into todos (id, name, due_date, priority, completed) values (1, 'Object-based context-sensitive implementation', '03/09/2021', 2, false);
insert into todos (id, name, due_date, priority, completed) values (2, 'Business-focused homogeneous productivity', '03/07/2021', 2, true);
insert into todos (id, name, due_date, priority, completed) values (3, 'Stand-alone empowering superstructure', '03/12/2021', 2, true);
insert into todos (id, name, due_date, priority, completed) values (4, 'Extended bifurcated moratorium', '03/21/2021', 2, true);
insert into todos (id, name, due_date, priority, completed) values (5, 'Exclusive grid-enabled encoding', '03/13/2021', 1, false);
insert into todos (id, name, due_date, priority, completed) values (6, 'Cross-group composite monitoring', '03/23/2021', 1, false);
insert into todos (id, name, due_date, priority, completed) values (7, 'Realigned bottom-line encryption', '03/18/2021', 2, true);
insert into todos (id, name, due_date, priority, completed) values (8, 'De-engineered dedicated flexibility', '03/23/2021', 1, false);
insert into todos (id, name, due_date, priority, completed) values (9, 'Universal intermediate algorithm', '03/08/2021', 2, false);
insert into todos (id, name, due_date, priority, completed) values (10, 'Team-oriented solution-oriented complexity', '03/25/2021', 1, false);
insert into todos (id, name, due_date, priority, completed) values (11, 'Organized methodical core', '03/14/2021', 1, false);
insert into todos (id, name, due_date, priority, completed) values (12, 'Inverse exuding internet solution', '03/15/2021', 3, true);
insert into todos (id, name, due_date, priority, completed) values (13, 'Programmable zero tolerance standardization', '03/27/2021', 3, true);
insert into todos (id, name, due_date, priority, completed) values (14, 'Profound client-server product', '03/14/2021', 3, true);
insert into todos (id, name, due_date, priority, completed) values (15, 'Reduced methodical emulation', '03/14/2021', 1, true);
insert into todos (id, name, due_date, priority, completed) values (16, 'De-engineered asynchronous contingency', '03/08/2021', 2, true);
insert into todos (id, name, due_date, priority, completed) values (17, 'Switchable eco-centric knowledge user', '03/27/2021', 1, false);
insert into todos (id, name, due_date, priority, completed) values (18, 'Programmable static collaboration', '03/09/2021', 3, true);
insert into todos (id, name, due_date, priority, completed) values (19, 'Profit-focused value-added info-mediaries', '03/16/2021', 3, false);
insert into todos (id, name, due_date, priority, completed) values (20, 'Universal 24 hour alliance', '03/20/2021', 2, true);
insert into todos (id, name, due_date, priority, completed) values (21, 'Fundamental reciprocal instruction set', '03/20/2021', 2, false);
insert into todos (id, name, due_date, priority, completed) values (22, 'Versatile explicit capability', '03/04/2021', 3, false);
insert into todos (id, name, due_date, priority, completed) values (23, 'Re-contextualized exuding policy', '03/07/2021', 3, true);
insert into todos (id, name, due_date, priority, completed) values (24, 'Triple-buffered foreground intranet', '03/03/2021', 3, true);
insert into todos (id, name, due_date, priority, completed) values (25, 'Open-source secondary installation', '03/27/2021', 1, false);
SELECT setval('todos_id_seq', 26);